baseURL = "https://www.lruchandani.com/"
languageCode = "en-us"
#title = "My learning and findings"
theme = "soho"
DisqusShortname = "lruchandani"

[params]
title = "Soho Theme"
#description = "Example Blog"
gravatar = "lalit.ruchandani@gmail.com"
images = ["images/profile.png"]
copyright = "Lalit Ruchandani"
#license = "CC BY-SA 4.0"
#licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["posts","cheatsheets"]
DisableComments = false

## Set custom theme color.
# themeColor = "#fc2803"

customCss = ["css/custom.css"]

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/lruchandani"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/lruchandani"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://github.com/lruchandani"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Cheatsheets"
  weight = 100
  identifier = "cheatsheets"
  url = "/cheatsheets/"

 [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
